onlinesale/carts/urls.py
from django.urls import path
from .views import update_cart,cart_home
urlpatterns = [
    path("update/", update_cart, name="update"),
    path("list/", cart_home, name="list"),
]

onlinesale/onlinesale/urls.py
from django.contrib import admin
from django.urls import path
from .views import home_page,about_page,contact_page
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import register_page,signin_page,signout_page
from django.conf.urls import include
from search.views import SearchProductListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",home_page,name="home"),
    path("about/",about_page,name="about"), 
    path("contact/",contact_page,name="contact"),
    path("register/",register_page,name="register"),
    path("signin/",signin_page,name="signin"),
    path("signout/",signout_page,name="signout"),
    path("product/",include(('products.urls','products'),namespace='product')),
    path("cart/", include(('carts.urls', 'carts'), namespace="cart")),
    path("search/", SearchProductListView.as_view(), name="search"),
    path("order/", include(('orders.urls', 'orders'), namespace="order")),
    path("address/",include(('addresses.urls','addresses'),namespace='address')),
    
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

onlinesale/products/urls.py
from django.urls import path
from .views import product_list,ProductListView,ProductDetailView

urlpatterns = [
    path("",product_list,name="fbv"),
    path("cbv/",ProductListView.as_view(),name="cbv"),
    path("<int:pk>/",ProductDetailView.as_view(),name="detail"),
    path("<str:slug>/",ProductDetailView.as_view(),name="detail"),
]

onlinesale/templates/layout/css.html
 <!-- Bootstrap CSS -->
 {% load static %}
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
 <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
 <link rel = "stylesheet" href ="{% static 'css/main.css' %}"/>

onlinesale/templates/layout/footer.html
<div class="footer">
  <p>&copy; 2019 Hardik</p>
</div>

onlinesale/templates/layout/js.html
 <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

onlinesale/templates/layout/layout.html
<!doctype html>
<html lang="en">
  <head>
        <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">       
    {% include 'layout/css.html' %}
    {% include 'layout/menu.html' %}   
    <title>Hello, world!</title>
  </head>
  <body>                       
        {% include 'layout/js.html' %}        
        {% block mainblock %}        
        {% endblock %}
        {% include 'layout/footer.html' %}
  </body>
  </html>

onlinesale/templates/layout/menu.html
{% load static %}
<style>
  .header{
    width: 100%;
    height: 100vh;
    background-image: url("{% static 'img/back.jpg' %}");
    background-repeat: no-repeat;
    background-size: 100% 100%;
    clip-path: polygon(100% 0%,100% 77%,50% 100%,0 75%,0 0);
    position: relative;
   }
.header:before{
  content: "";
  position: absolute;
  top: 20%;
  opacity: .3%%
  bottom: 0%;
  left: 0%;
  right:0%;
  z-index: -1;
  background:linear-gradient(to right,#1e5799 0%, #3ccdbb 0%, #16c9f6 100%);
 }
  nav {
    float: left;
    width: 100%;
    height: 438px; 
    background: #ccc;
    padding: 10px;
    opacity: .100%%;
  }

  nav ul {
    list-style-type: circle;
    padding: 10px;
  }

  @media (max-width: 600px) {
    nav, article {
      width: 100%;
      height: auto;
    }
  }
  ul {
    list-style-type: none;
    margin: 0;
    padding-left: 32%;
    overflow: hidden
    background-color: #003300;
    width: 100;
    font-size: 25px;
    opacity: .100%%
  }

  li {
    float: left;
  }

  li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
  }

  li a:hover {
    background-color: #111;
    border-style: solid;
    border-radius: 40px;
  }

 .border-10{
  border-color: black;
  border-style:solid;
  border-width: 2px;
  border-radius: 3px; 
  padding: 5px;
 }

</style>

<div class="header" id="topheader">
  <nav class="navbar navbar-expand-lg ">
  <div class="container text-uppercase">
    <a class="navbar-brand text-white font-weight-bold border-10" href="#">
      <!-- <img src="{% static 'img/logo.png' %}" width="50%" class="d-inline-block align-top" alt=""> -->
    </a>
 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent ">
    <ul class="navbar-nav ml-auto ">
      <li class="nav-item active">
        <a class="nav-link text-white" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link text-white" href="{% url 'about' %}">About <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link text-white" href="{% url 'contact' %}">Contact <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link text-white" href="{% url 'product:fbv' %}">FBV Products <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link text-white" href="{% url 'product:cbv' %}">CBV Products <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cart:list' %}">
          <i class="fa fa-shopping-cart" ></i>
        </a>
      </li>
      {% if request.user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link text-white" href="{% url 'signout' %}">sign out <span class="sr-only">(current)</span></a>
        </li>
      {% else %}
        <li class="nav-item active">
        <a class="nav-link text-white" href="{% url 'register' %}">sign up <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
        <a class="nav-link text-white" href="{% url 'signin' %}">sign in <span class="sr-only">(current)</span></a>
        </li>
      {% endif %}
    </ul>
    {% include 'search/search.html' with query=query %}
    </div>
  </div>
  </nav>
  <section class="header-section">
    <div class="center-div">
        <h1 class="font-weight-bold text-center text-white">Welcome to Hardik's Kitchen</h1>
        <p> We Create Hunger</p>
    </div>
</section>
 
</div>