onlinesale/carts/urls.py
from django.urls import path
from .views import update_cart,cart_home
urlpatterns = [
    path("update/", update_cart, name="update"),
    path("list/", cart_home, name="list"),
]

onlinesale/onlinesale/urls.py
from django.contrib import admin
from django.urls import path
from .views import home_page,about_page,contact_page
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import register_page,signin_page,signout_page
from django.conf.urls import include
from search.views import SearchProductListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",home_page,name="home"),
    path("about/",about_page,name="about"), 
    path("contact/",contact_page,name="contact"),
    path("register/",register_page,name="register"),
    path("signin/",signin_page,name="signin"),
    path("signout/",signout_page,name="signout"),
    path("product/",include(('products.urls','products'),namespace='product')),
    path("cart/", include(('carts.urls', 'carts'), namespace="cart")),
    path("search/", SearchProductListView.as_view(), name="search"),
    path("order/", include(('orders.urls', 'orders'), namespace="order")),
    path("address/",include(('addresses.urls','addresses'),namespace='address')),
    
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

onlinesale/orders/urls.py
from django.urls import path
from .views import create_order, received_payment

urlpatterns = [
    path("", create_order, name="create"),
    path("payment/", received_payment, name="payment"),
]

onlinesale/orders/models.py
from django.db import models
from billing.models import BillingProfile
from addresses .models import Address
from carts.models import Cart
from django.db.models.signals import pre_save
from products.utils import unique_orderid_generator
from decimal import Decimal

ORDER_STATUS_CHOICES = (('created','Order is created'),('paid','Payment Done!'))
# Create your models here.
class OrderManager(models.Manager):
    def get_or_new(self, cart_obj, bill_obj):
        order_obj = self.get_queryset().filter(cart=cart_obj, billingProfile=bill_obj, status='created').first() or None
        if order_obj is None:
            order_obj = self.get_queryset().create(cart=cart_obj, billingProfile=bill_obj)
        if order_obj.order_total != cart_obj.total:
            order_obj.update_order(cart_obj)
        return order_obj

class Order(models.Model):
    order_id = models.CharField(max_length=120, blank=True, unique=True) #ASFGHH3345678SDFGHJK
    billingProfile = models.ForeignKey(BillingProfile, on_delete=models.PROTECT)
    address = models.ForeignKey(Address, null=True, blank=True, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.PROTECT)
    status = models.CharField(max_length=20, default='created', choices=ORDER_STATUS_CHOICES)
    order_total = models.DecimalField(max_digits=8, decimal_places=2, default=0.0) #cart total
    total = models.DecimalField(max_digits=8, decimal_places=2,default=0.0)  # order_total + 18 % GST
    razor_pay_id = models.CharField(max_length=120,null=True, blank=True)

    objects = OrderManager()

    def __str__(self):
        return self.order_id

    def update_order(self,cart_obj):
        if self.order_total != cart_obj.total:
            self.order_total = cart_obj.total
            self.total = round(self.order_total * Decimal(1.18),2)
            self.save()

def orderid_pre_save_receiver(sender, instance, *args, **kwargs):
    if instance.order_id is None or instance.order_id=="":
        instance.order_id = unique_orderid_generator(instance)

pre_save.connect(orderid_pre_save_receiver, sender=Order)  

onlinesale/orders/views.py
from django.shortcuts import render
from django.http import HttpResponse
from carts.models import Cart
from billing.models import BillingProfile
from .models import Order
from accounts.forms import SignInForm
from addresses.forms import AddressForm
from addresses.models import Address

# Create your views here.
def create_order(request):
    loginform = SignInForm()
    addressForm = AddressForm()
    context = {"loginform":loginform,'addressForm':addressForm}
    cart_obj = Cart.objects.new_or_get(request)
    bill_obj = BillingProfile.objects.get_or_new(request)
    if cart_obj and bill_obj:
        order_obj = Order.objects.get_or_new(cart_obj, bill_obj)
        context['order_obj'] = order_obj
        add_list = Address.objects.filter(billing_profile=bill_obj)
        context['addList'] =add_list
    return render(request,"orders/placeorder.html",context)
    # return HttpResponse(order_obj)

def received_payment(request):
    print(request.POST)
    orderid = request.POST.get("shopping_order_id")
    payid = request.POST.get("razorpay_payment_id")
    # bill_obj = BillingProfile.objects.get_or_new(request)
    # cart_obj = Cart.objects.new_or_get(request)
    # order_obj = Order.objects.get_or_new(cart_obj, bill_obj)
    order_obj = Order.objects.filter(order_id=orderid).first()
    if order_obj:
        order_obj.razor_pay_id = payid
        order_obj.status = "paid"
        order_obj.save()
        del request.session['cart_id']
        context = {'orderid':orderid, 'payid':payid}
    return render(request, "orders/success.html", context)

onlinesale/orders/templates/orders/paynow.html
<form action="{% url 'order:payment' %}" method="POST">
    {% csrf_token %}
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_XDiInUIrJYACDo"
    data-amount="100"
    data-name="Itvedant Education Pvt. Ltd."
    data-description="Payment Details"
    data-buttontext="Pay Now"
    data-theme.color="#F37254"
    data-description=""
    data-prefill.name="{{ object.billingProfile.user.full_name }}"
    data-prefill.email="{{ object.billingProfile.email }}"
    data-prefill.contact="{{object.billingProfile.user.mobile}}"
    data-notes.shopping_order_id="{{object.order_id}}">
</script>
<input type="hidden" name="shopping_order_id" value="{{object.order_id}}">
</form>

onlinesale/orders/templates/orders/placeorder.html
{% extends 'layout/layout.html' %}
{% block mainblock %}
{% if request.user.is_authenticated %}
    <h3>Order ID : {{order_obj.order_id}}</h3>
    <h3>Sub Total : {{order_obj.order_total}}</h3>
    <h3>Total(18%) : {{order_obj.total}}</h3>
    {% if order_obj.address %}
        {{order_obj.address.get_address|linebreaks}}
        {% include 'orders/paynow.html' with object=order.obj%}
    {% else %}
        <div class="row">
            <div class="col">
                <h5>Add New Address</h5>
                {% include 'addresses/addAddress.html' with form=addressForm next_url=build_absolute_uri %}
            </div>
            <div class="col">
                <h5>Select Address</h5>
                {% include 'addresses/selectAddress.html' with addList=addList next_url=request.build_absolute_url %}
            </div>
        </div>
    {% endif %}
{% else %}
<div class="col-5">
    <form method="POST" action="{% url 'signin' %}">
        {% csrf_token %}
        {{loginform}}
        <input type="submit" value="Login" class="btn btn-primary"/>
        <input type="hidden" name="next_url" value="{{request.build_absolute_uri}}"/>
    </form>
</div>
{% endif %}
{% endblock %}

onlinesale/orders/templates/orders/success.html
{% extends 'layout/layout.html' %}
{% block mainblock %}
    <h3>Thank you for your order.</h3>
    <p> Please note the detail for future transaction</p>
    <h6>Order Id : {{orderid}}</h6>
    <h6>Payment Id : {{payid}}</h6>
{% endblock %}