onlinesale/carts/urls.py
from django.urls import path
from .views import update_cart,cart_home
urlpatterns = [
    path("update/", update_cart, name="update"),
    path("list/", cart_home, name="list"),
]

onlinesale/onlinesale/urls.py
from django.contrib import admin
from django.urls import path
from .views import home_page,about_page,contact_page
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import register_page,signin_page,signout_page
from django.conf.urls import include
from search.views import SearchProductListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",home_page,name="home"),
    path("about/",about_page,name="about"), 
    path("contact/",contact_page,name="contact"),
    path("register/",register_page,name="register"),
    path("signin/",signin_page,name="signin"),
    path("signout/",signout_page,name="signout"),
    path("product/",include(('products.urls','products'),namespace='product')),
    path("cart/", include(('carts.urls', 'carts'), namespace="cart")),
    path("search/", SearchProductListView.as_view(), name="search"),
    path("order/", include(('orders.urls', 'orders'), namespace="order")),
    path("address/",include(('addresses.urls','addresses'),namespace='address')),
    
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

onlinesale/orders/urls.py
from django.urls import path
from .views import create_order, received_payment

urlpatterns = [
    path("", create_order, name="create"),
    path("payment/", received_payment, name="payment"),
]

onlinesale/carts/models.py
from django.db import models

# Create your models here.
from django.db import models
# from django.contrib.auth.models import User
from products.models import Product
from decimal import Decimal
from django.db.models.signals import m2m_changed
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.
class CartManager(models.Manager):
    def new_or_get(self, request):
        cartid = request.session.get('cart_id', None)
        if cartid is not None:
            cart_obj = Cart.objects.filter(id=cartid).first()
        elif request.user.is_authenticated:
            cart_obj=Cart.objects.filter(user=request.user).first()
            if cart_obj is None:
                cart_obj = Cart.objects.create(user=request.user)
            request.session['cart_id'] = cart_obj.id
        else:
            cart_obj = Cart.objects.create()
            request.session['cart_id'] = cart_obj.id
        
        return cart_obj

class Cart(models.Model):
    user        = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    products    = models.ManyToManyField(Product, blank=True)
    subtotal    = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total       = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    updated     = models.DateTimeField(auto_now=True)
    created   = models.DateTimeField(auto_now_add=True)
    
    
    
    objects = CartManager()
    def __str__(self):
        return str(self.id)

def products_m2m_changed_receiver(sender, instance, *args, **kwargs):
    instance.subtotal = Decimal(0)
    for prod in instance.products.all():
        instance.subtotal += prod.price
    if instance.subtotal < Decimal(500):
        instance.total = instance.subtotal + Decimal(80)
    else:
        instance.total = instance.subtotal
    instance.save()

m2m_changed.connect(products_m2m_changed_receiver, sender=Cart.products.through)

onlinesale/carts/views.py
from django.shortcuts import render, redirect
from products.models import Product
from .models import Cart
def cart_home(request):
    cart_obj = Cart.objects.new_or_get(request)
    context={'cart_obj':cart_obj}
    return render(request, "carts/list.html",context)

def update_cart(request):
    cart_obj = Cart.objects.new_or_get(request)
    if request.method == 'POST':
        prodid = request.POST.get('prodid')
        if prodid:
            prod_obj = Product.objects.filter(id=prodid).first()
            #query set select * from carts_cart_products where cart_id = cartid
            if prod_obj in cart_obj.products.all():
                #remove
                cart_obj.products.remove(prod_obj)
            else:
                #add
                cart_obj.products.add(prod_obj)
    return redirect('cart:list')

onlinesale/carts/templates/carts/list.html
{% extends 'layout/layout.html' %}
{% block mainblock %}
    {% if cart_obj.products.all %}
    <table class="table">
        <tr>
            <th>#</th>
            <th>Name</th>
            <th></th>
            <th>Quantity</th>
            <th>Price</th>
                    
        </tr>
        {% for prod in cart_obj.products.all %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{prod.title}}</td>
                    <td>{% include 'products/snippets/addtocart.html' with pid=prod.id in_cart=True %} </td>
                    <td><input type="number"></td>
                    <td>{{prod.price}}</td>

                </tr>
            {% endfor %}
            <tr>
                <td colspan="3"><b>Subtotal</b></td>
                <td>{{cart_obj.subtotal}}</td>
            </tr>
            <tr>
                <td colspan="3"><b>Total</b></td>
                <td>{{cart_obj.total}}</td>
            </tr>
          
        </table>
        <form method="POST" action="{% url 'order:create' %}">
            {% csrf_token %}
            <input type="submit" value="Order Now" class="btn btn-primary"/>
        </form>
    {% else %}
        <h1>Cart is empty</h1>
    {% endif %}
    {% endblock %}